### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by OthnielDona**
Website Translation, done and dusted.
@nioperas06 waiting for review.

### CODE REVIEW

**Comment by nioperas06** [comment]
Thank you :+1:

**Comment by nioperas06** [comment]
This pull request broke the deployment pipeline on Netlify.

**Comment by OthnielDona** [comment]
Do we know why?

**Comment by nioperas06** [comment]
No, I'm double-checking everything.

**Comment by OthnielDona** [comment]
Ok

**Pull request merged**
